{
    #Type of Solution
    "isPlanar": true
}

{   # Dimensions of the domain
    "X Length": 1002,
    "Y Length": 1,
    "Z Length": 1002,


    "X Resolution": 0.001,
    "Y Resolution": 0.001,
    "Z Resolution": 0.001,

    "Courant factor": 0.57735026919,

    "Number of timesteps": 4000,

    "Use Plane Wave": false
}

{   # Parellelization parameters
    "X Number of Procs": 4,
    "Y Number of Procs": 1,
    "Number of Threads per node": 1
}
