{
    #Type of Solution
    "isPlanar": false
}

{   # Dimensions of the domain
    "X Length": 102,
    "Y Length": 102,
    "Z Length": 102,


    "X Resolution": 0.001,
    "Y Resolution": 0.001,
    "Z Resolution": 0.001,

    "Courant factor": 0.57735026919,

    "Number of timesteps": 500,

    "Use Plane Wave": true
}

{   # Parellelization parameters
    "X Number of Procs": 1,
    "Y Number of Procs": 1,
    "Number of Threads per node": 1
}
