{
    #Type of Solution
    "isPlanar": true,

    #applicable only when planar is true
    "isTransverseElectric": true
}

{   # Dimensions of the domain
    "X Length": 42,
    "Y Length": 42,
    "Z Length": 42,


    "X Resolution": 0.001,
    "Y Resolution": 0.001,
    "Z Resolution": 0.001,

    "Courant factor": 0.57735026919,

    "Number of timesteps": 3
}

{   # Parellelization parameters
    "X Number of Procs": 2,
    "Y Number of Procs": 2,
    "Number of Threads per node": 2
}
